[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install"]

[phases.build]
cmds = ["pnpm prisma:generate", "pnpm build"]

[start]
cmd = "pnpm prisma:migrate && pnpm seed && pnpm start"
